# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  SOLARGRAPH_CACHE: ${{ github.workspace }}/vendor/solargraph/cache
  BUNDLE_PATH: ${{ github.workspace  }}/vendor/bundle

jobs:
  test:
    name: Tests (ruby v${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3', '3.4', '4.0', 'head']

    steps:
      - name: Checkout solargraph-rspec
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          rubygems: latest
          bundler-cache: false

      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: ${{ env.BUNDLE_PATH }}
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec.gemspec') }}-${{ hashFiles('solargraph-rspec.gemspec') }}-${{ hashFiles('.github/workflows/ruby.yml') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec.gemspec') }}-${{ hashFiles('solargraph-rspec.gemspec') }}-${{ hashFiles('.github/workflows/ruby.yml') }}
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec.gemspec') }}-${{ hashFiles('solargraph-rspec.gemspec') }}
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec.gemspec') }}-
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-
            bundle-use-ruby-${{ matrix.os }}-

      - name: Install dependencies
        run: |
          set -x
          bundle config path ${{ env.BUNDLE_PATH }}
          bundle install --jobs 4 --retry 3 # we need this to install appraisal
          bundle exec appraisal bundle config path ${{ env.BUNDLE_PATH }}
          bundle exec appraisal install --jobs 4 --retry 3
          # Test the bleeding edge so that we can catch integration issues early
          if [ ${{ matrix.ruby-version }} == 'head' ]
          then
            # test bleeding edge against bleeding edge to find
            # integration issues
            bundle exec appraisal bundle update --pre solargraph rbs
          end
          bundle exec appraisal rbs --version
          bundle exec appraisal solargraph --version
          # For some reason on ruby 3.1 it defaults to an old version: 1.3.2
          # https://github.com/lekemula/solargraph-rspec/actions/runs/17814581205/job/50645370316?pr=22

      - name: Run Rubocop
        # https://github.com/rubocop/rubocop/issues/10893#issuecomment-1952517060
        run: bundle exec rubocop --restart-server

      - name: Cache Solargraph YARD and RBS pins for gems
        uses: actions/cache@v4
        with:
          path: ${{ env.SOLARGRAPH_CACHE }}
          key: os-${{ runner.os }}-ruby-${{ matrix.ruby-version }}-solargraph-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            os-${{ runner.os }}-ruby-${{ matrix.ruby-version }}-solargraph-${{ hashFiles('**/Gemfile.lock') }}
            os-${{ runner.os }}-ruby-${{ matrix.ruby-version }}-solargraph-

      - name: Configure .solargraph.yml
        run: cp .solargraph.yml.example .solargraph.yml

      - name: Solargraph generate RSpec gems YARD and RBS pins
        run: |
          rspec_gems=$(bundle exec appraisal bundle exec ruby -r './lib/solargraph-rspec' -e 'puts Solargraph::Rspec::Gems.gem_names.join(" ")' 2>/dev/null | tail -n1)
          bundle exec appraisal bundle exec solargraph gems $rspec_gems

      - name: Run tests
        run: |
          # we don't need byebug in CI; byebug requires readline
          # support in Ruby which doesn't always appear in the Ruby
          # installed by ruby/setup-ruby
          export NO_DEBUG=true
          bundle exec appraisal rspec --format progress

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: solargraph-rspec/coverage
