# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  SOLARGRAPH_CACHE: "${{ github.workspace }}/solargraph-rspec/gem-cache"
  BUNDLE_GEMFILE: "${{ github.workspace }}/solargraph-rspec/gemfiles/default.gemfile"

jobs:
  test:
    name: Tests (ruby v${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # FIXME: Why '3.0' is not working with Appraisal?
        # FIXME: Add 'head' https://github.com/lekemula/solargraph-rspec/pull/8/commits/3b52752b96e7f2ec01831406f8e5a51c91523187 
        ruby-version: ['3.1', '3.2', '3.3']
    steps:
      - name: Checkout solargraph-rspec
        uses: actions/checkout@v4
        with:
          path: solargraph-rspec

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      # FIXME: Why caching for ruby 2.6 and 2.7 is not working after setting up appraisals?
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: solargraph-rspec/gemfiles/vendor/bundle
          key: bundle-use-ruby-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec/Gemfile', 'solargraph-rspec/gemfiles/default.gemfile.lock') }}

      - name: Install dependencies
        run: |
          cd solargraph-rspec
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # - name: Run Rubocop
      #   run: cd solargraph-rspec && bundle exec rubocop

      - name: 'Apply solargraph debug patch'
        run: |-
          echo 'exclude: ["vendor/**/*", "gemfiles/**/*"]' > solargraph-rspec/.solargraph.yml
          cd solargraph-rspec/gemfiles/vendor/bundle/ruby/${{ matrix.ruby-version }}.0/gems/solargraph-0.56.0

          awk '/Caching yardoc for/ { print "return nil unless Dir.exist?(gemspec.gem_dir)"; print; next }1' lib/solargraph/yardoc.rb > tmp.rb
          mv tmp.rb lib/solargraph/yardoc.rb

      - name: Cache Docs
        run: |-
          cd solargraph-rspec
          bundle exec solargraph gems --rebuild

      - name: Run tests
        run: cd solargraph-rspec && bundle exec rspec --format progress

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: solargraph-rspec/coverage
