# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
name: Ruby

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    name: Tests (ruby v${{ matrix.ruby-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.6", "2.7", "3.1"]

    steps:
      - name: Checkout solargraph-rspec
        uses: actions/checkout@v4
        with:
          path: solargraph-rspec

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: false

      # FIXME: Why caching for ruby 2.6 and 2.7 is not working after setting up appraisals?
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: solargraph-rspec/vendor/bundle
          key: bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec/Gemfile.lock', 'solargraph-rspec/gemfiles/*.gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-${{ matrix.os }}-${{ matrix.ruby-version }}-${{ hashFiles('solargraph-rspec/Gemfile.lock', 'solargraph-rspec/gemfiles/*.gemfile.lock') }}

      - name: Install dependencies
        run: |
          cd solargraph-rspec
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec appraisal install

      - name: Run Rubocop
        run: cd solargraph-rspec && bundle exec rubocop

      - name: Set up yardocs
        # yard gems caches the yardocs into <gem_path>/doc/.yardoc path, hence they should be cached by ruby gems cache 
        run: cd solargraph-rspec && bundle exec appraisal yard gems --verbose

      - name: List all Yardoc constants and methods
        run: |
            cd solargraph-rspec
            bundle exec yard list

      - name: Run tests
        run: cd solargraph-rspec && bundle exec appraisal rspec --format progress

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: solargraph-rspec/coverage
